bump mender to 5.0.0
also:
  - Bump mender-artifact to 4.0.0
  - Bump mender-connect to 2.3.0
  - Bump mender-update-modules to latest version and add options for the new
    modules

diff --git a/buildroot-external-mender/board/common/post-image-include b/buildroot-external-mender/board/common/post-image-include
--- a/buildroot-external-mender/board/common/post-image-include
+++ b/buildroot-external-mender/board/common/post-image-include
@@ -117,7 +117,7 @@ parse_args() {
         (-g|--generate-mender-image) GENERATE_MENDER_IMAGE="${2}"; shift 2;;
         (-t|--device-type) DEVICE_TYPE="${2}"; shift 2;;
         (--) shift; break;;
-        *) exit 1;;
+        *) echo "Invalid option!" exit 1;;
         esac
     done
 }
